CREATE TABLE public.catalog_cards (id text PRIMARY KEY, player text NOT NULL, club text NOT NULL, season text NOT NULL, manufacturer text NOT NULL, collection text NOT NULL, card_number text NOT NULL, image text NOT NULL, illustrative boolean NOT NULL DEFAULT true);
GRANT SELECT ON public.catalog_cards TO anon, authenticated;
GRANT ALL ON public.catalog_cards TO service_role;
ALTER TABLE public.catalog_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY catalog_public_read ON public.catalog_cards FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE public.card_variants (id text PRIMARY KEY, card_id text NOT NULL REFERENCES public.catalog_cards(id), parallel text NOT NULL, print_run integer CHECK (print_run > 0), autograph boolean NOT NULL DEFAULT false);
GRANT SELECT ON public.card_variants TO anon, authenticated;
GRANT ALL ON public.card_variants TO service_role;
ALTER TABLE public.card_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY variants_public_read ON public.card_variants FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '' CHECK (char_length(display_name) <= 80));
GRANT SELECT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profile_read_own ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY profile_update_own ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE FUNCTION public.create_private_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN INSERT INTO public.profiles(id, display_name) VALUES (NEW.id, left(coalesce(NEW.raw_user_meta_data->>'display_name', ''), 80)); RETURN NEW; END; $$;
REVOKE ALL ON FUNCTION public.create_private_profile() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER create_private_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_private_profile();
INSERT INTO public.profiles(id, display_name) SELECT id, left(coalesce(raw_user_meta_data->>'display_name', ''), 80) FROM auth.users ON CONFLICT (id) DO NOTHING;
CREATE TABLE public.physical_copies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL DEFAULT auth.uid(), variant_id text NOT NULL REFERENCES public.card_variants(id), condition text NOT NULL DEFAULT 'Não informada' CHECK (char_length(condition) BETWEEN 1 AND 80), serial text NOT NULL DEFAULT '' CHECK (char_length(serial) <= 40), grading text NOT NULL DEFAULT 'Sem graduação' CHECK (char_length(grading) BETWEEN 1 AND 80), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.physical_copies TO authenticated;
GRANT ALL ON public.physical_copies TO service_role;
ALTER TABLE public.physical_copies ENABLE ROW LEVEL SECURITY;
CREATE POLICY copies_own ON public.physical_copies FOR ALL TO authenticated USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);
CREATE INDEX copies_owner_variant ON public.physical_copies(owner_id, variant_id);
CREATE TABLE public.wishlist (user_id uuid NOT NULL DEFAULT auth.uid(), variant_id text NOT NULL REFERENCES public.card_variants(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id, variant_id));
GRANT SELECT, INSERT, DELETE ON public.wishlist TO authenticated;
GRANT ALL ON public.wishlist TO service_role;
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY wishlist_own ON public.wishlist FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
INSERT INTO public.catalog_cards(id,player,club,season,manufacturer,collection,card_number,image) VALUES ('vini','Vinícius Júnior','Real Madrid','2023/24','Topps','Topps Chrome UEFA','#10','/demo-cards/card-1.jpg'),('pele','Pelé','Seleção Brasileira','2022','Panini','Panini Prizm World Cup','#25','/demo-cards/card-2.jpg'),('messi','Lionel Messi','Seleção Argentina','2022','Panini','Panini Prizm World Cup','#1','/demo-cards/card-3.jpg'),('cr7','Cristiano Ronaldo','Manchester United','2022/23','Panini','Panini Select','#7','/demo-cards/card-4.jpg'),('ney','Neymar Jr.','Paris Saint-Germain','2022/23','Topps','Topps Chrome UEFA','#11','/demo-cards/card-5.jpg'),('endrick','Endrick','Palmeiras','2023','Panini','Panini Select','#9','/demo-cards/card-6.jpg');
INSERT INTO public.card_variants(id,card_id,parallel,print_run,autograph) VALUES ('vini-gold','vini','Gold',50,false),('vini-base','vini','Base',null,false),('pele-green','pele','Green',99,true),('messi-silver','messi','Silver',null,false),('cr7-red','cr7','Red',199,false),('ney-blue','ney','Blue',150,true),('endrick-base','endrick','Base',null,false);