COMMENT ON TABLE public.physical_copies IS 'Physical seller inventory, independent of purchased collection. Existing rows retained; no manual purchased-collection flow.';
CREATE TABLE public.purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), buyer_id uuid NOT NULL, seller_id uuid NOT NULL, copy_id uuid NOT NULL REFERENCES public.physical_copies(id), status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','shipped','received','cancelled')), created_at timestamptz NOT NULL DEFAULT now(), received_at timestamptz);
GRANT SELECT ON public.purchase_orders TO authenticated;
GRANT ALL ON public.purchase_orders TO service_role;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY orders_participants_read ON public.purchase_orders FOR SELECT TO authenticated USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
CREATE INDEX orders_buyer ON public.purchase_orders(buyer_id);
CREATE TABLE public.purchased_collection (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, order_id uuid NOT NULL UNIQUE REFERENCES public.purchase_orders(id), copy_id uuid NOT NULL UNIQUE REFERENCES public.physical_copies(id), acquired_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.purchased_collection TO authenticated;
GRANT ALL ON public.purchased_collection TO service_role;
ALTER TABLE public.purchased_collection ENABLE ROW LEVEL SECURITY;
CREATE POLICY acquired_owner_read ON public.purchased_collection FOR SELECT TO authenticated USING (auth.uid() = owner_id);
CREATE INDEX purchased_owner ON public.purchased_collection(owner_id);
CREATE FUNCTION public.validate_received_acquisition() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.purchase_orders o WHERE o.id = NEW.order_id AND o.buyer_id = NEW.owner_id AND o.copy_id = NEW.copy_id AND o.status = 'received' AND o.received_at IS NOT NULL) THEN RAISE EXCEPTION 'Acquisition requires a matching received order'; END IF; RETURN NEW; END; $$;
REVOKE ALL ON FUNCTION public.validate_received_acquisition() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER received_acquisition_guard BEFORE INSERT OR UPDATE ON public.purchased_collection FOR EACH ROW EXECUTE FUNCTION public.validate_received_acquisition();
CREATE POLICY acquired_copy_read ON public.physical_copies FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.purchased_collection a WHERE a.copy_id = physical_copies.id AND a.owner_id = auth.uid()));
COMMENT ON TABLE public.purchased_collection IS 'Private cards acquired through confirmed received platform orders. Users cannot manually add rows. Future verified fulfillment will write here.';
COMMENT ON TABLE public.purchase_orders IS 'Future direct sales and auction fulfillment; no checkout, payment, bidding or client status changes implemented.';