/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as CardIdRouteImport } from './routes/card.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/colecao': typeof ColecaoRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/colecao': typeof ColecaoRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/colecao': typeof ColecaoRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/colecao'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/card/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/colecao'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/card/$id'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/colecao'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/card/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  ColecaoRoute: typeof ColecaoRoute
  ExplorarRoute: typeof ExplorarRoute
  MercadoRoute: typeof MercadoRoute
  PerfilRoute: typeof PerfilRoute
  CardIdRoute: typeof CardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  ColecaoRoute: ColecaoRoute,
  ExplorarRoute: ExplorarRoute,
  MercadoRoute: MercadoRoute,
  PerfilRoute: PerfilRoute,
  CardIdRoute: CardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
