/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedColecaoRouteImport } from './routes/_authenticated/colecao'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedMeusAnunciosRouteImport } from './routes/_authenticated/meus-anuncios'
import { Route as CardIdRouteImport } from './routes/card.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedColecaoRoute = AuthenticatedColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusAnunciosRoute =
  AuthenticatedMeusAnunciosRouteImport.update({
    id: '/meus-anuncios',
    path: '/meus-anuncios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/colecao': typeof AuthenticatedColecaoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/colecao': typeof AuthenticatedColecaoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anunciar': typeof AnunciarRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/colecao': typeof AuthenticatedColecaoRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/card/$id': typeof CardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/auth'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/reset-password'
    | '/colecao'
    | '/compras'
    | '/favoritos'
    | '/meus-anuncios'
    | '/card/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/auth'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/reset-password'
    | '/colecao'
    | '/compras'
    | '/favoritos'
    | '/meus-anuncios'
    | '/card/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anunciar'
    | '/auth'
    | '/explorar'
    | '/mercado'
    | '/perfil'
    | '/reset-password'
    | '/_authenticated/colecao'
    | '/_authenticated/compras'
    | '/_authenticated/favoritos'
    | '/_authenticated/meus-anuncios'
    | '/card/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnunciarRoute: typeof AnunciarRoute
  AuthRoute: typeof AuthRoute
  ExplorarRoute: typeof ExplorarRoute
  MercadoRoute: typeof MercadoRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CardIdRoute: typeof CardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/colecao': {
      id: '/_authenticated/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof AuthenticatedColecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-anuncios': {
      id: '/_authenticated/meus-anuncios'
      path: '/meus-anuncios'
      fullPath: '/meus-anuncios'
      preLoaderRoute: typeof AuthenticatedMeusAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedColecaoRoute: typeof AuthenticatedColecaoRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMeusAnunciosRoute: typeof AuthenticatedMeusAnunciosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedColecaoRoute: AuthenticatedColecaoRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMeusAnunciosRoute: AuthenticatedMeusAnunciosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnunciarRoute: AnunciarRoute,
  AuthRoute: AuthRoute,
  ExplorarRoute: ExplorarRoute,
  MercadoRoute: MercadoRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CardIdRoute: CardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
